name: Determine Changed Files

on:
  push:
    branches: 'main'

  workflow_dispatch:

jobs:
  determine-changes:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Get changes
        run: |
          $file_array = @( git diff --name-only ${{ github.event.before }} ${{ github.event.after }}` )
          foreach ($file_item in $file_array) {
            Write-Output "the following is different: $file_item"
          }
          
