name: Determine Changed Files

on:
  push:
    branches: 'main'

  workflow_dispatch:

jobs:
  determine-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Get changes
        run: |
          echo TODO: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          str_var=`git diff --name-only ${{ github.event.before }} ${{ github.event.after }}`
          echo $str_var
          IFS=$'\n' read -d "\034" -r -a arr_var <<<"${str_var}\034"
          for i in "${!arr_var[@]}"; do
            echo "$i => ${arr_var[$i]}"
          done
