name: Determine Changed Files

on:
  push:
    branches: 'main'

  workflow_dispatch:

jobs:
  determine-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Get changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
