name: Determine Changed Files

on:
  push:
    branches: 'main'

  workflow_dispatch:

jobs:
  determine-changes:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Get changes
        run: |
          # Write-Output "TODO: WINDOWS: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}"
          $watch_files = @("file1.md", "file2.md")
          Write-Output "Event Name: ${{ github.event_name }}"
          if("${{ github.event_name }}" -eq "workflow_dispatch") {
            #Write-Output "non-push: use HEAD~1..HEAD, which isn't as specific, but better than nothing"
            $changed_files = @( git diff --name-only HEAD~1..HEAD )
          } else {
            #Write-Output "for-push: use before/after"
            $changed_files = @( git diff --name-only ${{ github.event.before }} ${{ github.event.after }} )
          }
          foreach ($this_file in $changed_files) {
            Write-Output "the following is different: $this_file"
            if( $this_file -in $watch_files ) {
              Write-Output "we care about the changes in: $this_file"
            }
          }
          
