name: Trigger Target Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="pryrt" 
          repo_name="receiverRepo"  
          event_type="trigger-workflow" 
          #service="${{ github.event.inputs.target_service }}"
          #version="${{ github.event.inputs.target_version }}"
          ref_name="${{ github.ref_name }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TRIGGER_WORKFLOW }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/target_workflow.yml/dispatches \
            -d "{\"ref\": \"$ref_name\", \"inputs\": { \"in_opt\": \"This is the remote message\" }}"
