name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="pryrt" 
          repo_name="receiverRepo"  
          event_type="trigger-workflow" 
          service="${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
          ref_name="${{ github.ref_name }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TRIGGER_WORKFLOW }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/target_workflow.yml/dispatches \
            -d "{\"ref\": \"$ref_name\", \"inputs\": {}}"

          echo API-docs version of curl command:
          echo curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <YOUR-TOKEN>" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW_ID/dispatches \
            -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'

          echo my edited version of curl command:
          echo curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TRIGGER_WORKFLOW }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/target_workflow.yml/dispatches \
            -d "{\"ref\": \"$ref_name\", \"inputs\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
